spring.application.name=help-desk

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/help_desk
spring.datasource.username=root
spring.datasource.password=Balaji@2001
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql: true